version: "3"
services:
  dotlive:
    image: node:15
    restart: unless-stopped
    working_dir: /home/node/app
    volumes:
    - ./:/home/node/app
    environment:
      FRAMES_DIR: frames.dick
      FRAME_MS: 200
    ports:
    - 8938:3000
    command: "npm start"
